[package]
name = "stranger-jail"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bollard = "0.19.3"
futures-util = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
